-- all available game states
STATE_GAME = 0
STATE_CHANGELVL = 1
STATE_CHANGELVL_2 = 2
STATE_ENDING = 3
STATE_ENDTOCRE = 4
STATE_CREDITS = 5
STATE_GAMETOEND = 6
STATE_MENU = 7
STATE_MENUTOGAME = 8
STATE_MENUTOEXIT = 9
STATE_GOVER = 10
STATE_GAMETOGOVER = 11
STATE_GOVERTOGAME = 12
STATE_GOVERTOMENU = 13
STATE_ENDINGTOMENU = 14
STATE_PAUSED = 15

STATE_TRANS_STUB = 98
STATE_DETRANS_STUB = 99